name: demo_pipeline
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_2
  - attrs=24.3.0=py313h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - blinker=1.9.0=py313h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py313h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py313h06a4308_0
  - datasets=3.3.2=py313h06a4308_0
  - dill=0.3.8=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - flask=3.1.0=py313h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - fsspec=2024.12.0=py313h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - huggingface_hub=0.29.2=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - itsdangerous=2.2.0=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - multidict=6.1.0=py313h5eee18b_0
  - multiprocess=0.70.15=py313h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.10.1=py313h3c60e43_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - pillow=11.1.0=py313hac6e08b_1
  - pip=25.0=py313h06a4308_0
  - propcache=0.3.1=py313h5eee18b_0
  - protobuf=5.29.3=py313he621ea3_0
  - pyarrow=19.0.0=py313h6a678d5_1
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=0_cp313
  - pytz=2024.1=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py313h5eee18b_0
  - requests=2.32.3=py313h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py313h8a85203_0
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py313hb8e4a85_0
  - tqdm=4.67.1=py313h7040dfc_0
  - transformers=4.49.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - werkzeug=3.1.3=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py313h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.6.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asttokens==3.0.0
      - av==14.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - decord==0.6.0
      - depth-pro==0.1
      - einops==0.8.1
      - executing==2.2.0
      - fastapi==0.115.12
      - fonttools==4.57.0
      - h11==0.16.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - iopath==0.1.10
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mediapy==1.2.4
      - mpmath==1.3.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow-heif==0.22.0
      - portalocker==3.1.1
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-multipart==0.0.20
      - qwen-vl-utils==0.0.11
      - sam-2==1.0
      - scikit-image==0.25.2
      - scipy==1.15.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.46.2
      - style==1.1.0
      - sympy==1.14.0
      - tifffile==2025.3.30
      - timm==1.0.15
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-inspection==0.4.0
      - update==0.0.1
      - uvicorn==0.34.2
      - wcwidth==0.2.13