name: opentad4
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.12=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - afsd==1.0
      - align1d==2.5.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - amqp==5.3.1
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - av==16.0.1
      - beautifulsoup4==4.14.2
      - billiard==4.2.2
      - celery==5.5.3
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - decord==0.6.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.120.0
      - ffmpeg-python==0.2.0
      - filelock==3.14.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.1.10
      - hiredis==3.3.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.0
      - imgaug==0.4.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - lazy-loader==0.4
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmaction2==1.1.0
      - mmcv-lite==2.0.1
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.3
      - ninja==1.13.0
      - nms-1d-cpu==0.0.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - parameterized==0.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorchvideo==0.1.5
      - pytz==2023.4
      - pyyaml==6.0.3
      - redis==5.2.1
      - regex==2025.10.23
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - sentry-sdk==2.42.1
      - setuptools==60.2.0
      - shapely==2.1.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.48.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0+cu128
      - torchaudio==2.9.0+cu128
      - torchvision==0.24.0+cu128
      - tqdm==4.65.2
      - transformers==4.57.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.38.0
      - vine==5.1.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - yacs==0.1.8
      - yapf==0.43.0