name: dfine2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - anyio==4.11.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - boxmot==12.0.7
      - calflops==0.3.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cmake==4.0.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - faster-coco-eval==1.6.5
      - filelock==3.18.0
      - filterpy==1.4.5
      - flask==3.1.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - lapx==0.5.11.post1
      - lit==18.1.8
      - loguru==0.7.3
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - narwhals==1.38.2
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.0.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yacs==0.1.8
